AWSTemplateFormatVersion: 2010-09-09
Description: Script to create a SSL certificate and Cloudfront distribution.
###############################################################################
Parameters:
###############################################################################
  DomainName:
    Type: String
    Description: Root Domain name for your website (example.com)
    Default: webapp.example.com

  
###############################################################################
Resources:
###############################################################################

  Cert:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      SubjectAlternativeNames: 
        - !Join ['', ['*.', !Ref DomainName]]
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          ValidationDomain: !Ref DomainName
      ValidationMethod: DNS