AWSTemplateFormatVersion: '2010-09-09'
###############################################################################
Parameters:
###############################################################################
  CertStackName:
    Description: Name of the base stack with ACM certificate
    Type: String
    Default: cert

  DomainName:
    Type: String
    Description: Root Domain name for your website (example.com)
    Default: webapp.example.com
  PriceClass:

    Type: String
    Description: The CloudFront distribution price class
    Default: 'PriceClass_200'
    AllowedValues:
      - 'PriceClass_100'
      - 'PriceClass_200'
      - 'PriceClass_All'
###############################################################################
Resources:
###############################################################################
  myDNS:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId:
        Ref: myHostedZoneID
      RecordSets:
      - Name:
          Ref: DomainName
        Type: A
        AliasTarget:
          HostedZoneId: Z3AQJSTF
          DNSName:
            !GetAtt: myDistribution.DomainName
  Cert:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      SubjectAlternativeNames: 
        - !Join ['', ['*.', !Ref DomainName]]
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          ValidationDomain: !Ref DomainName
      ValidationMethod: DNS

  myDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
        - DomainName: !Join ['', [!Ref DomainName, '.s3.amazonaws.com']]
          Id: !Join ['', ['S3-', !Ref DomainName]]
          S3OriginConfig:
            OriginAccessIdentity: ''
        Enabled: 'true'
        Comment: Some comment
        DefaultRootObject: index.html
        Logging:
          IncludeCookies: 'false'
          Bucket: mylogs.s3.amazonaws.com
          Prefix: !Ref DomainName
        Aliases:
        - !Ref DomainName
        DefaultCacheBehavior:
          AllowedMethods:
          - DELETE
          - GET
          - HEAD
          - OPTIONS
          - PATCH
          - POST
          - PUT
          TargetOriginId: !Join ['', ['S3-', !Ref DomainName]]
          ForwardedValues:
            QueryString: 'false'
            Cookies:
              Forward: none
          ViewerProtocolPolicy: allow-all
        PriceClass: !Ref PriceClass
        ViewerCertificate:
          # CloudFrontDefaultCertificate: 'false'
          SslSupportMethod: 'sni-only'
          # IamCertificateId: 'false'
          AcmCertificateArn: !Ref 'Cert'
            # Fn::ImportValue:
            #   Fn::Sub: "${CertStackName}-CERT"

###############################################################################
Outputs:
###############################################################################
  AcmCertARN:
    Description: ACM certificate ARN
    Value: 
      Ref: Cert
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-CERT"
  CfntDistributionURL:
    Value: !Ref myDistribution
    Description: URL for CloudFront Distribuitions